#!/usr/bin/env bash
# https://hiphish.github.io/blog/2020/05/23/how-i-manage-ssh-connections/

export FZF_DEFAULT_OPTS='
--height=20%
--reverse
--prompt="SSH > "
--preview="awk -v HOST={} -f ~/.ssh/bin/host2conf.awk ~/.ssh/config"'

host=$(grep '^[[:space:]]*Host[[:space:]]' ~/.ssh/config | cut -d ' ' -f 2 | fzf)
host_name=$(echo $host | tr . _)
echo $host_name

if [[ -z $host ]]; then
    exit 0
fi

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $host_name "eval \"$(ssh-agent -s)\" && ssh \"$host\""
    exit 0
fi

if ! tmux has-session -t=$host_name 2> /dev/null; then
    tmux new-session -ds $host_name "eval \"$(ssh-agent -s)\" && ssh \"$host\""
fi

tmux switch-client -t $host_name
